version: '3.9'

services:
  whatsapp-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whats-bot
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - whatsapp-data:/app/data
    env_file:
      - .env

volumes:
  whatsapp-data:
